### ISSUE TITLE
How do I download my model to local because huggingface keeps downloading errors

### ISSUE THREAD

**Issue by caissonfiv** [kijai/ComfyUI-SUPIR#10]
I found that ckpt_pth.py can fill in the address, but I don't know where to download.

**Comment by cdb-boop** [comment]
It's listed on the [original project repo](https://github.com/Fanghua-Yu/SUPIR?tab=readme-ov-file#dependent-models), but it's a bit vague. Here's my understanding.

1. For **SDXL_CLIP1_PTH**, you need a path to a folder containing files from [`openai/clip-vit-large-patch14`](https://huggingface.co/openai/clip-vit-large-patch14):
- config.json
- merges.txt
- model.safetensors
- special_tokens_map.json
- tokenizer.json
- tokenizer_config.json
- vocab.json

2. For **SDXL_CLIP2_CKPT_PTH** you only need a path to the model file itself from [`laion/CLIP-ViT-bigG-14-laion2B-39B-b160k`](https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k). I don't think this one currently works with the safetensors version.
- open_clip_pytorch_model.bin

**Comment by Sostay** [comment]
> It's listed on the [original project repo](https://github.com/Fanghua-Yu/SUPIR?tab=readme-ov-file#dependent-models), but it's a bit vague. Here's my understanding.
> 
> 1. For **SDXL_CLIP1_PTH**, you need a path to a folder containing files from [`openai/clip-vit-large-patch14`](https://huggingface.co/openai/clip-vit-large-patch14):
> 
> * config.json
> * merges.txt
> * model.safetensors
> * special_tokens_map.json
> * tokenizer.json
> * tokenizer_config.json
> * vocab.json
> 
> 2. For **SDXL_CLIP2_CKPT_PTH** you only need a path to the model file itself from [`laion/CLIP-ViT-bigG-14-laion2B-39B-b160k`](https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k). I don't think the code currently works with the safetensors version.
> 
> * open_clip_pytorch_model.bin

Which path should I put in the local place after the download?

**Comment by kijai** [comment]
No download should be required anymore, CLIP models are loaded from the SDXL checkpoint instead.
