### ISSUE TITLE
 about the tiled quailty

### ISSUE THREAD

**Issue by K-O-N-B** [kijai/ComfyUI-SUPIR#105]
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/152141077/652d0de7-b54a-42fd-98c5-91b480be5c70)

what can I do for fix this....?

**Comment by kijai** [comment]
Did you use tile stride?

**Comment by K-O-N-B** [comment]
> tile stride

I guess no.....I even don't where is it.....

I just use the default workflow, just change the sampler to tiledrestoredpmpp2msampler.

<img width="1340" alt="image" src="https://github.com/kijai/ComfyUI-SUPIR/assets/152141077/4f01e9cc-8111-49ca-afe7-f17887b45b68">

**Comment by kijai** [comment]
> > tile stride
> 
> I guess no.....I even don't where is it.....
> 
> I just use the default workflow, just change the sampler to tiledrestoredpmpp2msampler.
> 
> <img alt="image" width="1340" src="https://private-user-images.githubusercontent.com/152141077/322220442-4f01e9cc-8111-49ca-afe7-f17887b45b68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNDA1NjYsIm5iZiI6MTcxMzA0MDI2NiwicGF0aCI6Ii8xNTIxNDEwNzcvMzIyMjIwNDQyLTRmMDFlOWNjLTgxMTEtNDljYS1hZmU3LWYxNzg4N2I0NWI2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QyMDMxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWQ4MmViOGIyNDUxNGY2OWQ0MGZiNTYyYTA2OThkZWJiZGE4ZmZhYzhiNDBlZDg3OTVlNzgzYzVlOTBlZjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2LyyJUSXuDXifaItxZE8tyX_FwX6xdlkXIIQJWaDrI8">

Weird, in the sampler you seem to have tile stride set to tile size.. which effectively disables stride and you get the borders, stride should be half of the tile size.

**Comment by K-O-N-B** [comment]
help..... all the images higher then 6K will like this.

![image](https://github.com/kijai/ComfyUI-SUPIR/assets/152141077/7935568b-f959-4ff0-8852-764b896add55)


TiledRestoreEDMSampler is better, but still can't use.

![image](https://github.com/kijai/ComfyUI-SUPIR/assets/152141077/cf67a073-022d-49e0-8ec0-343e9ecf297d)

**Comment by bigcat88** [comment]
Can you provide a source image to test on?

**Comment by K-O-N-B** [comment]
upscale 2x and 3x pls.

![ComfyUI_temp_zjcqu_00002_](https://github.com/kijai/ComfyUI-SUPIR/assets/152141077/c5c95c72-49b5-49b7-b590-7098c5a896c2)

**Comment by bigcat88** [comment]
[output_00016_.heic.zip](https://github.com/kijai/ComfyUI-SUPIR/files/15214106/output_00016_.heic.zip)

Was only able to do 2x upscaling, 64Gb of RAM is not enough to make `4608х8064` as a result.
And due to GitHub limit of 10Mb I uploaded it as a heic in zip..

**Comment by yushan777** [comment]
Also no problems here.  I think your tile stride is too high, it should be lower than the tile size (think of it as the overlap between tiles to help blending). 

Another thing is that I think SUPIR more of a detailer better-suited to photographic images (where minute details are more critical).  Art styles probably don't need SUPIR and you can maybe away with other upscalers.  Having said that, it is no slouch either way.

**Comment by K-O-N-B** [comment]
got it.
