### ISSUE TITLE
When I run it, I have to download a file first, 10g.

### ISSUE THREAD

**Issue by tanglup** [kijai/ComfyUI-SUPIR#16]
![22f](https://github.com/kijai/ComfyUI-SUPIR/assets/160642431/bc3e551f-ecbf-405b-9119-b0236e598188)
Isn’t it normal? I still don’t need it.

**Comment by kijai** [comment]
Yep, it's the clipG file that's needed, it's downloaded from here: https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/tree/main

**Comment by tanglup** [comment]
> 是的，这是需要的clipG文件，从这里下载：https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/tree/main
After downloading, which folder should this file be placed  in?

**Comment by tanglup** [comment]
> 是的，这是需要的clipG文件，从这里下载： https: [//huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/tree/main](https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/tree/main)

After downloading, which folder should you put it in?

**Comment by kijai** [comment]
> > 是的，这是需要的clipG文件，从这里下载： https: [//huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/tree/main](https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/tree/main)
> 
> After downloading, which folder should you put it in?

For now you can put that file anywhere, get the .bin file only and edit the CKPT_PTH.py like so (just an example):
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/40791699/c9de366d-7b99-4873-a75a-21434c39380d)

**Comment by kijai** [comment]
On Windows the path might need to use double lashes instead ` \\`

**Comment by tanglup** [comment]
> 在 Windows 上，路径可能需要使用双睫毛代替` \\`

//, how to use, on windows, give an example

**Comment by kijai** [comment]
> > 在 Windows 上，路径可能需要使用双睫毛代替` \\`
> 
> //, how to use, on windows, give an example

Example:
`SDXL_CLIP2_CKPT_PTH = "C:\\ComfyUI_windows_portable\\ComfyUI\\models\\clip\\open_clip_pytorch_model.bin"`

**Comment by tanglup** [comment]
> > > 在Windows上，路径可能需要使用双互连代替` \\`
> > 
> > 
> > //、如何使用，在windows上，举个例子
> 
> 例子： `SDXL_CLIP2_CKPT_PTH = "C:\\ComfyUI_windows_portable\\ComfyUI\\models\\clip\\open_clip_pytorch_model.bin"`

The path above resolves successfully, but a new error appears:
Error occurred when executing SUPIR_Upscale:

Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper_CUDA___slow_conv2d_forward)

**Comment by kijai** [comment]
This should finally be fixed now, the clip models will be loaded from the SDXL checkpoint instead.
