### ISSUE TITLE
The generated image looks like an abstract painting

### ISSUE THREAD

**Issue by aitormendez** [kijai/ComfyUI-SUPIR#163]
![Captura de pantalla 2024-09-15 a las 8 58 38](https://github.com/user-attachments/assets/88c776d0-0e5b-4063-844f-44b237c9da83)

The same configuration with the same models works perfectly on the legacy node:

![Captura de pantalla 2024-09-15 a las 7 42 03](https://github.com/user-attachments/assets/936c7811-08b5-4fed-a663-46f411967d39)

Is there any error in the workflow? Thanks!

**Comment by kijai** [comment]
You are missing the image rescaling which should be the first operation done to the image, the old node had that built-in. Check the example workflow.

**Comment by aitormendez** [comment]
Yes! Thank you so much. It works as espected.

![Captura de pantalla 2024-09-15 a las 11 23 13](https://github.com/user-attachments/assets/80895b6f-f595-42b0-a42b-03b84bb46b9f)
