### ISSUE TITLE
Comfyui crashes after initializing embedder

### ISSUE THREAD

**Issue by GuusDeKroon** [kijai/ComfyUI-SUPIR#22]
Hey!
On a fresh ComfyUI install, whenever I run the script, it seems to load the FrozenCLIPembedder, and then stop the script. What could be causing this?

> Total VRAM 24564 MB, total RAM 32693 MB
> xformers version: 0.0.24
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
> VAE dtype: torch.bfloat16
> Using xformers cross attention
> 
> Import times for custom nodes:
>    3.3 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188
> got prompt
> Diffusion using bf16
> Encoder using bf16
> Building a Downsample layer with 2 dims.
>   --> settings are:
>  in-chn: 320, out-chn: 320, kernel-size: 3, stride: 2, padding: 1
> constructing SpatialTransformer of depth 2 w/ 640 channels and 10 heads
> constructing SpatialTransformer of depth 2 w/ 640 channels and 10 heads
> Building a Downsample layer with 2 dims.
>   --> settings are:
>  in-chn: 640, out-chn: 640, kernel-size: 3, stride: 2, padding: 1
> constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
> constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
> constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
> constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
> constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
> constructing SpatialTransformer of depth 10 w/ 1280 channels and 20 heads
> constructing SpatialTransformer of depth 2 w/ 640 channels and 10 heads
> constructing SpatialTransformer of depth 2 w/ 640 channels and 10 heads
> constructing SpatialTransformer of depth 2 w/ 640 channels and 10 heads
> Initialized embedder #0: FrozenCLIPEmbedder with 123060480 params. Trainable: False
> 
> E:\AI\ComfyUI_windows_portable>pause
> Press any key to continue . . .

![comfy](https://github.com/kijai/ComfyUI-SUPIR/assets/49596150/bf1eadfa-5c46-4fd8-9a9a-597deb63ef83)
Thanks for your help already ^^

**Comment by kijai** [comment]
On that point it loads the huge CLIP model (the bigG), if it's not in your hugginface cache it will download it, in the console you should see the process, it will take a while. I'm looking into handling all that better.

**Comment by kijai** [comment]
This should finally be fixed by now. Reopen if not.
