### ISSUE TITLE
bfloat16 error

### ISSUE THREAD

**Issue by Ziov** [kijai/ComfyUI-SUPIR#3]
Getting this error how can I correct it?

Error occurred when executing SUPIR_Upscale:

"upsample_nearest2d_out_frame" not implemented for 'BFloat16'

**Comment by kijai** [comment]
Seems the default colorfix "Wavelet" doesn't work with bf16, try using AdIn or None instead.

**Comment by Ziov** [comment]
same issue

**Comment by kijai** [comment]
Then I don't know, it's working for me and for someone else who had the same error initially after switching to Adain.

**Comment by kijai** [comment]
Added manual way to set the dtypes now, maybe it helps if you just use fp16 for diffusion like in the original.

**Comment by GraftingRayman** [comment]
You will need 16GB of VRAM, also, install tensorflow 

pip install tensorflow

That will get rid of the float error

**Comment by kijai** [comment]
> You will need 16GB of VRAM, also, install tensorflow
> 
> pip install tensorflow
> 
> That will get rid of the float error

VRAM use depends entirely on the resolution used, I was able to run 512p -> 1024p with 10GB gpu for example. On a 24GB largest I've done has been 3000x3000, probably lots of optimization to do still though.

**Comment by Ziov** [comment]
getting the same error with memory leaks, my comfyui is giving the same input images and outputs when not using the node, fails when using it I also tried add Tensoflow but Same issue, images are 832x1216 on RTX 4080 16gb, Ryzen 9 7950x, 64gb DDR5 and Win 11

**Comment by kijai** [comment]
> getting the same error with memory leaks, my comfyui is giving the same input images and outputs when not using the node, fails when using it I also tried add Tensoflow but Same issue, images are 832x1216 on RTX 4080 16gb, Ryzen 9 7950x, 64gb DDR5 and Win 11

Do you have xformers installed? If not you should try installing/updating it with:

`pip install -U xformers --no-dependencies`

or if you use the portable install:

`python_embeded\python.exe -m pip install xformers --no-dependencies`

Also make sure the node is updated, it's very much work in progress but current version should work.

**Comment by Ziov** [comment]
So I've been unable to fix it, but its causing so many problems with my Comfy install as its causing major memory loops, keep getting the same outputs "tried different browsers / cleared cookies and cache", it breaks the auto generate function too even after deleting the install folder and doing a new install, what package has it installed that I could uninstall from Python?

**Comment by kijai** [comment]
What auto generate function? Getting same outputs from what? Nothing in this node could possibly affect that when it's not used, you can see what's installed in the requirements.txt. The problem isn't in this node as it works fine with the latest ComfyUI as it is, conflicts with other nodes are of course possible.

If you installed xformers and didn't use it before, that could cause issues with some setups.
