### ISSUE TITLE
White orb artifacts when upscaling merged dreambooth trained jug v9 checkpoints (needs fp16 fix vae selection option?)

### ISSUE THREAD

**Issue by brentjohnston** [kijai/ComfyUI-SUPIR#33]
I had this issue before where I would dreambooth train over juggernaut v9 and do a model merge, with another db trained checkpoint. (only an issue when jug v9 is involved with their baked vae)

White orbs would appear. To fix it I use the [SDXL fp16 fixed vae.](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/tree/main) it would also fix the orange haze. 

The problem is I don't see any way to change the VAE being used in the supir node. I am not sure if it's just using the baked vae in the model.  Is there any way to specify a vae in the node? I would prefer not to retrain a bunch of the models, as they came out before jugg v9, but I merge a little juggernaut at a very low 0.05 and it improves the db quality a ton.

I am unsure if fp16 supported for supir though, it seems like it's using bf16 when I checked the nodes.py?

Here's what happens when using any dreambooth trained checkpoint that has any juggernaut v9 merges and upscaling with supir (this is not the subject):

Low res:
![test](https://github.com/kijai/ComfyUI-SUPIR/assets/23625562/c33a3243-833d-46a1-a738-b07076210b06)
Upscaled:
![testupscale-jug-merged-db-checkpoint](https://github.com/kijai/ComfyUI-SUPIR/assets/23625562/aa05aa2a-b4d1-401a-8b7a-3fed22d1b5a8)

**Comment by brentjohnston** [comment]
I found a workaround fix.

```
1. Go to Checkpoint merger tab.
2. Load your model from the "Primary model (A)" dropdown.
3. Set a name (Optional)
4. Slide the "Multiplier (M)" slider to: 0
5. Under "Interpolation Method" select: No interpolation
6. Enable: Save as float16 if needed
7. The default option for a "Bake in VAE" is: None (Leave it or select the fp16 vae fix)
8. Click the "Merge"
```

**Comment by kijai** [comment]
It seems the VAE in the SDXL checkpoint selected is indeed fully used, the SUPIR model only has keys for "denoise_encoder", so rest is from SDXL like usual.

While this is a valid issue, I don't think it's in the scope of this wrapper node currently as it can be dealt with by just baking in a working VAE like you did. Eventually I would like to implement this properly in Comfy, so things like this wouldn't be an additional issue.
