### ISSUE TITLE
Support for 8gb VRAM and 16gb ram system

### ISSUE THREAD

**Issue by Archit01** [kijai/ComfyUI-SUPIR#34]
Is there a way to make it work on 8gb vram system with 16 gb ram. I have rtx 2060 super 8gb vram and 16 gb system memory.

**Comment by kijai** [comment]
I'm afraid not, VRAM **maybe** could be enough with tiling smaller tiles, but 16GB system RAM just is not.

**Comment by Archit01** [comment]
requirements are pretty high for this at least for consumer end systems!! Thank you for the support by the way.

**Comment by kijai** [comment]
Yeah they are, that is not up to me though, it's just how it is. Tiling possibly can make it run, but it would be incredibly slow then.
