### ISSUE TITLE
Xformer version not compatible with comfyUI torch version

### ISSUE THREAD

**Issue by JYLCode** [kijai/ComfyUI-SUPIR#35]
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.0+cu121 with CUDA 1201 (you have 2.1.2+cu121)
    Python  3.11.7 (you have 3.11.6)

I tried upgrading Torch for Comfy and it crashed comfy completely

**Comment by kijai** [comment]
It clearly says you have old torch, so it's not updated?

`pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

with portable comfy:
`python_embeded\python.exe pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

xformers 0.0.24 will complain about torch too 2.2.1 but it still seems to work.

**Comment by JYLCode** [comment]
I originally updated by python_embeded\python.exe -m pip install torch but then Comfy failed to load after; had a traceback in torch,py

python_embeded\python.exe -m pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

command worked for me though, Thanks Kijai!

**Comment by kijai** [comment]
You're welcome! Reason was that on Windows you have to specify the cuda url or it installs CPU version.
