### ISSUE TITLE
The quality doesn't feel as good as the replicate version

### ISSUE THREAD

**Issue by reb1302** [kijai/ComfyUI-SUPIR#37]
I apologize for this question, I have done a lot of testing and follow your daily updates closely. I keep updating and I want to have quality like the replicate version or the one-click install on Patreon. I really like your versions because they are flexible on comfy UI, easy to mix with other features, but I have done many tests and the results are far from the input image.

**Comment by stephantual** [comment]
Out of curiosity, what do you mean by 'replicate version on a one click install on Patreon"?

**Comment by Sumsar3** [comment]
There is another open issue with more info and examples. Take a look and comment with photo examples if you can
