### ISSUE TITLE
Isn't there two text encoders in the SDXL model? Why do we need to download them separately?

### ISSUE THREAD

**Issue by wodsoe** [kijai/ComfyUI-SUPIR#38]
Isn't there two text encoders in the SDXL model? Why do we need to download them separately?

**Comment by kijai** [comment]
I would like to know this too, question better suited for the original repo. I don't personally see any reason for this, but I could be wrong. My hope is that we can separate the pieces that make SUPIR tick (mostly the controlnet) and implement it properly in comfy.

**Comment by kijai** [comment]
Figured out a way to do this, the clip models will be loaded from the SDXL checkpoint now.

**Comment by driqeks** [comment]
please mention in the readme that the clip models don't need to be downloaded, I downloaded them all because the readme implied thats required...
