### ISSUE TITLE
Is it possible to have model loading as a separate input node？

### ISSUE THREAD

**Issue by amimi818** [kijai/ComfyUI-SUPIR#42]
Is it possible to have model loading as a separate input node, so that it can share the model loading node with previous workflows such as t2i ？

Also, I don't know what happens between the following two steps, it takes so long (about 20+ seconds on my 4090)。
<img width="1011" alt="image" src="https://github.com/kijai/ComfyUI-SUPIR/assets/133093934/47f653e1-bca2-4412-9b9b-cd0be1a9e745">

thx

**Comment by kijai** [comment]
The original code that's wrapped with this node is highly inefficient in model loading, unlike native ComfyUI model loading. It's also not compatible as it is so we can't use the comfy model loaders with it. I'm hoping to better integrate this in the future, or maybe someone else will, in the end SUPIR is just a VAE and controlnet, so as a wrapper node this is highly inefficient way to use it in comfy.

**Comment by amimi818** [comment]
> The original code that's wrapped with this node is highly inefficient in model loading, unlike native ComfyUI model loading. It's also not compatible as it is so we can't use the comfy model loaders with it. I'm hoping to better integrate this in the future, or maybe someone else will, in the end SUPIR is just a VAE and controlnet, so as a wrapper node this is highly inefficient way to use it in comfy.

I see, thanks.

**Comment by kijai** [comment]
Not exactly what was asked, but for now the most I will do about this is done: the clip models are loaded from the SDXL checkpoint instead, I have no idea why they initially did not do that. Loading is way faster and I added global unload at beginning of this node so it should work in other workflows, albeit that is of course inefficient, but such is the nature of mere wrapper nodes.
