### ISSUE TITLE
Error occurred when executing SUPIR_Upscale:  No module named 'ComfyUI-SUPIR'

### ISSUE THREAD

**Issue by yanjie12344553** [kijai/ComfyUI-SUPIR#44]
![屏幕截图 2024-03-07 181548](https://github.com/kijai/ComfyUI-SUPIR/assets/122593221/9ec56546-ae8f-4582-be49-2931f3e2f9b5)

**Comment by kijai** [comment]
Rename the custom node folder to exactly `ComfyUI-SUPIR`

**Comment by kijai** [comment]
Also added fix for this in the latest commit, the folder name should be autodetected, tho I still recommend using the original intended name `ComfyUI-SUPIR`
