### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by laidingq** [kijai/ComfyUI-SUPIR#5]
Error occurred when executing SUPIR_Upscale:

maximum recursion depth exceeded while calling a Python object

---------------------------------------------------------------------------
After the update, it cannot run anymore. Before this, everything could run smoothly

**Comment by kijai** [comment]
Current version is working fine here, if you had the node in a workflow and updated then the node might need to be re-created.

**Comment by laidingq** [comment]
I have updated the newly created node flow

**Comment by laidingq** [comment]
And before the error occurs, it runs very slowly

**Comment by kijai** [comment]
Gonna need the whole error, it suggests that there's a loop somewhere.

**Comment by kijai** [comment]
Found it, my mistake, should be fixed now.

**Comment by kijai** [comment]
> Thank you for your work, I suggest you explain the parameter settings of this node if you like

I will once I learn them myself, I really haven't had time to test it all yet, parameters are just exposed like they were with the original code.

**Comment by laidingq** [comment]
Awesome, thank you
