### ISSUE TITLE
omegaconf

### ISSUE THREAD

**Issue by Deepcake-io** [kijai/ComfyUI-SUPIR#51]
Can you please tell me what could be the problem? I am trying to install SUPIR on COMFY UI. I get an error:
"from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf' "
I installed requirements.txt via cd \ComfyUI\custom_nodes\ComfyUI-SUPIR>
I also installed it separately in the same path \ComfyUI\custom_nodes\ComfyUI-SUPIR>.
pip install omegaconf==2.1 and pip install --upgrade omegaconf
and still the error
hence the SUPIR node does not appear in the interface ...
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/85621975/d9e0958e-7a53-40e8-bdc7-daea79444096)

**Comment by kijai** [comment]
I haven't used StabilityMatrix so I don't know how it handles the python environments, if just `pip install ` didn't work then it is not using your system python environment but it's own, and you would need to install requirements in that.

**Comment by Deepcake-io** [comment]
I managed to install it in the directory  C:\work\AI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\Scripts\activate

**Comment by kijai** [comment]
> I managed to install it in the directory C:\work\AI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\Scripts\activate

Okay good to know, that sounds right indeed.

**Comment by Oleksa25** [comment]
> I managed to install it in the directory C:\work\AI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\Scripts\activate

Please tell me how exactly you did it? How did you install it?
