### ISSUE TITLE
Error occurred when executing SUPIR_Upscale:

### ISSUE THREAD

**Issue by youxiaohanpian** [kijai/ComfyUI-SUPIR#52]
Error occurred when executing SUPIR_Upscale:
![Snipaste_2024-03-11_19-02-23](https://github.com/kijai/ComfyUI-SUPIR/assets/75460335/3269bde5-df05-4e79-8c30-29530a4dac4d)

'captions'

File "D:\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ezXY\autoCastPatch.py", line 295, in map_node_over_list
_nums = [str(value) for value in input_data_all[input_name]]
~~~~~~~~~~~~~~^^^^^^^^^^^^
Could you help me to fix it, thank you

**Comment by kijai** [comment]
Some conflict with a custom node pack you have installed called `ComfyUI_ezXY`, I don't know what that is and why it does this, disabling it should help.

**Comment by youxiaohanpian** [comment]
> Some conflict with a custom node pack you have installed called `ComfyUI_ezXY`, I don't know what that is and why it does this, disabling it should help.

I updated all it worked, thank you
