### ISSUE TITLE
About omegaconf issues

### ISSUE THREAD

**Issue by YuiLearnAI** [kijai/ComfyUI-SUPIR#53]
Hi, I have some problems about install ComfyUI-SUPIR.
I just git clone from ComfyUI-SUPIR, and install every requirement this node needs, then I run ComfyUI.
![Snipaste_2024-03-11_22-38-50](https://github.com/kijai/ComfyUI-SUPIR/assets/163010331/2a905ab9-396c-46a7-8e26-a0df150eaade)

But it just goes wrong, warning like this:

Says: 
` ModuleNotFoundError: No module named ‘omegaconf’ `
![1](https://github.com/kijai/ComfyUI-SUPIR/assets/163010331/c36fd5c5-777a-4ebc-996a-b814f2190208)

But When I checked my environment about omegaconf,  it shows the requirement have already satisfied.
![2](https://github.com/kijai/ComfyUI-SUPIR/assets/163010331/49d4e179-03cd-4d47-8d67-11d1f1fed115)

So, I boot up ComfyUI but can't create any SUPIR nodes.

Please help get it right, Thank you so much. 

(My ComfyUI and ComfyUI-SUPIR version is latest.)

**Comment by kijai** [comment]
That did not install in the portable environment for some reason, as it says it's satisfied in your Windows users folder. Double check there is a python.exe in that folder you're trying to launch it with, for some reason your command used system python anyway.

**Comment by YuiLearnAI** [comment]
Thanks a lot! 

I just remove my \AppData\Roaming\Python environment and reinstall the requirement.

Finally, it works!
