### ISSUE TITLE
Sizes of tensors must match except in dimension 1

### ISSUE THREAD

**Issue by Deepcake-io** [kijai/ComfyUI-SUPIR#54]
I would be very grateful if you have any suggestions on how to do this
![изображение](https://github.com/kijai/ComfyUI-SUPIR/assets/85621975/2eb3beb4-67f9-4511-acac-a97db9e15c89)
![изображение](https://github.com/kijai/ComfyUI-SUPIR/assets/85621975/60c20b1e-40d5-4c5e-8401-2c55ec463075)
I would be very grateful if you have any suggestions on how to do this

**Comment by kijai** [comment]
There was an error in my auto resize logic, should be fixed now, try updating and running again.

**Comment by Deepcake-io** [comment]
Thank you. its work)
