### ISSUE TITLE
Error occurred when executing SUPIR_Upscale - Sizes of tensors must match except in dimension 1. 

### ISSUE THREAD

**Issue by web2299** [kijai/ComfyUI-SUPIR#59]
> Error occurred when executing SUPIR_Upscale:
> 
> Sizes of tensors must match except in dimension 1. Expected size 134 but got size 133 for tensor number 1 in the list.
> 
> File "C:\Comfy\ComfyUI\execution.py", line 152, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\execution.py", line 82, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\execution.py", line 75, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes.py", line 333, in process
> samples = self.model.batchify_sample(imgs, caps, num_steps=steps,
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
> return func(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\custom_nodes\ComfyUI-SUPIR\SUPIR\models\SUPIR_model.py", line 143, in batchify_sample
> _samples = self.sampler(denoiser, noised_z, cond=c, uc=uc, x_center=z_stage1, control_scale=control_scale,
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\modules\diffusionmodules\sampling.py", line 439, in __call__
> x = self.sampler_step(
> ^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\modules\diffusionmodules\sampling.py", line 416, in sampler_step
> denoised = self.denoise(x, denoiser, sigma_hat, cond, uc, control_scale=control_scale)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\modules\diffusionmodules\sampling.py", line 398, in denoise
> denoised = denoiser(*self.guider.prepare_inputs(x, sigma, cond, uc), control_scale)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\custom_nodes\ComfyUI-SUPIR\SUPIR\models\SUPIR_model.py", line 131, in
> denoiser = lambda input, sigma, c, control_scale: self.denoiser(
> ^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\modules\diffusionmodules\denoiser.py", line 73, in __call__
> return network(input * c_in, c_noise, cond, control_scale) * c_out + input * c_skip
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
> return self._call_impl(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
> return forward_call(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\custom_nodes\ComfyUI-SUPIR\sgm\modules\diffusionmodules\wrappers.py", line 96, in forward
> out = self.diffusion_model(
> ^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
> return self._call_impl(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
> return forward_call(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\custom_nodes\ComfyUI-SUPIR\SUPIR\modules\SUPIR_v0.py", line 641, in forward
> h = self.project_modules[adapter_idx](control[control_idx], _h, h, control_scale=control_scale)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
> return self._call_impl(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
> return forward_call(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Comfy\ComfyUI\custom_nodes\ComfyUI-SUPIR\SUPIR\modules\SUPIR_v0.py", line 95, in forward
> h_raw = th.cat([h_ori, h], dim=1)
> ^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by rotatorotator** [comment]
What are your node settings ?

**Comment by web2299** [comment]
I think the problem was the input image wasnt size width/height in 64 step (512, 576, 640...) . Thanks anyway !

**Comment by kijai** [comment]
> I think the problem was the input image wasnt size width/height in 64 step (512, 576, 640...) . Thanks anyway !
> 
> btw can i use some kind of node that can do this 64 steps resize automatically ? sorry i am pretty new with Comfy !

It should be done automatically, but it rounds up always. If you want to ensure it yourself, this node has the option: 
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/40791699/cede3ea9-de4d-4053-906f-fed39a7c11b5)

**Comment by web2299** [comment]
Thank you [kijai](https://github.com/kijai) !
