### ISSUE TITLE
module 'comfy.model_management' has no attribute 'should_use_bf16'

### ISSUE THREAD

**Issue by tanglup** [kijai/ComfyUI-SUPIR#6]
Error occurred when executing SUPIR_Upscale:

module 'comfy.model_management' has no attribute 'should_use_bf16'
Note: I use the portable package comfyui,cuda11.8
Please tell me how to solve this problem

**Comment by kijai** [comment]
That means your ComfyUI is too old, you would have to update it.

**Comment by TheNeObr** [comment]
same problem here.... 
all up to date

i rebuild all confy... same error.

** ComfyUI startup time: 2024-02-29 23:14:32.870793
** Platform: Windows
** Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
** Python executable: D:\SD\ComfyUI\venv\Scripts\python.exe
** Log path: D:\SD\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\SD\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: D:\SD\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32608 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention

Error occurred when executing SUPIR_Upscale:

module 'comfy.model_management' has no attribute 'should_use_bf16'

File "D:\SD\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\SD\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\SD\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\SD\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes.py", line 99, in process
if comfy.model_management.should_use_bf16():

**Comment by kijai** [comment]
`module 'comfy.model_management' has no attribute 'should_use_bf16'`
Your ComfyUI can not be up to date if this function does not exist, it was added 2 weeks ago in this commit:
https://github.com/comfyanonymous/ComfyUI/commit/f83109f09bec04f39f028c275b4eb1231adba00a#diff-c43913f04f43d976f3ec095cfcb3981df79c55947e3efbe70799cd374905c773
