### ISSUE TITLE
AttributeError: 'MemoryEfficientAttnBlock' object has no attribute 'group_norm'

### ISSUE THREAD

**Issue by arlechinu** [kijai/ComfyUI-SUPIR#7]
Hi!

Was hoping to give this a test, been running into this error and can't really figure out what's going on, perhaps you could make sense of it?

Error occurred when executing SUPIR_Upscale:

'MemoryEfficientAttnBlock' object has no attribute 'group_norm'

File "D:\ComfyUI02\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes.py", line 168, in process
samples = self.model.batchify_sample(resized_image[i].unsqueeze(0), captions_list, num_steps=steps, restoration_scale= restoration_scale, s_churn=s_churn,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\ComfyUI\custom_nodes\ComfyUI-SUPIR\SUPIR\models\SUPIR_model.py", line 118, in batchify_sample
_z = self.encode_first_stage_with_denoise(x, use_sample=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\ComfyUI\custom_nodes\ComfyUI-SUPIR\SUPIR\models\SUPIR_model.py", line 56, in encode_first_stage_with_denoise
h = self.first_stage_model.denoise_encoder(x)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\ComfyUI\custom_nodes\ComfyUI-SUPIR\SUPIR\utils\tilevae.py", line 703, in __call__
return self.vae_tile_forward(x)
^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\ComfyUI\custom_nodes\ComfyUI-SUPIR\SUPIR\utils\tilevae.py", line 586, in wrapper
ret = fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\ComfyUI\custom_nodes\ComfyUI-SUPIR\SUPIR\utils\tilevae.py", line 936, in vae_tile_forward
tile = task[1](tile)
^^^^^^^^^^^^^
File "D:\ComfyUI02\ComfyUI\custom_nodes\ComfyUI-SUPIR\SUPIR\utils\tilevae.py", line 374, in
task_queue.append(('attn', lambda x, net=net: attn_forward_new_pt2_0(net, x)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI02\ComfyUI\custom_nodes\ComfyUI-SUPIR\SUPIR\utils\tilevae.py", line 197, in attn_forward_new_pt2_0
if self.group_norm is not None:
^^^^^^^^^^^^^^^
File "D:\ComfyUI02\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

**Comment by kijai** [comment]
I have not ran into this specific one, but here's a list of things to check/try:

- update the node, and ComfyUI itself
- check/update pytorch version, I've used 2.2.X cu121 successfully
- xformers seem to be required, try installing it with:
`pip install -U xformers --no-dependencies`
- try switching dtypes
- try with tiled_vae off
- update nvidia drivers

If all else fails, you can give me the output of your python env by doing

 `pip list`

**Comment by arlechinu** [comment]
- comfyui up to date, updated before installing the node
- not sure about pytorch version - how to update?
- getting warning in console Attention mode 'softmax-xformers' is not available. Falling back to native attention. This is not a problem in Pytorch >= 2.0. FYI, you are running with PyTorch version 2.1.0+cu121

- xformers installed
- nvidia drivers up to date

- dtypes - Error occurred when executing SUPIR_Upscale: fp16 cause NaN in AE or some other errors when on fp32

- tiled_vae off - Error occurred when executing SUPIR_Upscale: name 'xformers' is not defined

- comfyui is saying Using pytorch cross attention - do I need to use xformers instead? add it to commandline args or something?

Package            Version
------------------ -----------
accelerate         0.22.0
certifi            2023.5.7
charset-normalizer 3.1.0
colorama           0.4.6
controlnet-aux     0.0.7
diffusers          0.21.0.dev0
einops             0.6.1
filelock           3.12.3
fsspec             2023.9.0
huggingface-hub    0.17.1
idna               3.4
imageio            2.31.3
importlib-metadata 6.8.0
Jinja2             3.1.2
keyboard           0.13.5
lazy_loader        0.3
MarkupSafe         2.1.3
mpmath             1.3.0
networkx           3.1
numpy              1.25.0
opencv-python      4.8.0.76
packaging          23.1
Pillow             9.5.0
pip                24.0
psutil             5.9.5
pyeaze             0.8.1
PyWavelets         1.4.1
pywin32            306
PyYAML             6.0.1
regex              2023.8.8
requests           2.31.0
safetensors        0.3.3
scikit-image       0.21.0
scipy              1.10.1
setuptools         63.2.0
six                1.16.0
sympy              1.12
tifffile           2023.8.30
timm               0.9.7
tokenizers         0.13.3
torch              2.0.1
torchvision        0.15.2
tqdm               4.66.1
transformers       4.33.1
typing_extensions  4.7.1
urllib3            2.0.3
websockets         10.4
wxPython           4.2.1
xformers           0.0.24
zipp               3.16.2

**Comment by arlechinu** [comment]
Tried updating torch and still getting errors, can't seem to enable xformers in comfyui. 

Package            Version
------------------ ------------
accelerate         0.22.0
certifi            2023.5.7
charset-normalizer 3.1.0
colorama           0.4.6
controlnet-aux     0.0.7
diffusers          0.21.0.dev0
einops             0.6.1
filelock           3.12.3
fsspec             2023.9.0
huggingface-hub    0.17.1
idna               3.4
imageio            2.31.3
importlib-metadata 6.8.0
Jinja2             3.1.2
keyboard           0.13.5
lazy_loader        0.3
MarkupSafe         2.1.3
mpmath             1.3.0
networkx           3.1
numpy              1.25.0
opencv-python      4.8.0.76
packaging          23.1
Pillow             9.5.0
pip                24.0
psutil             5.9.5
pyeaze             0.8.1
PyWavelets         1.4.1
pywin32            306
PyYAML             6.0.1
regex              2023.8.8
requests           2.31.0
safetensors        0.3.3
scikit-image       0.21.0
scipy              1.10.1
setuptools         63.2.0
six                1.16.0
sympy              1.12
tifffile           2023.8.30
timm               0.9.7
tokenizers         0.13.3
torch              2.2.1+cu121
torchaudio         2.2.1+cu121
torchvision        0.17.1+cu121
tqdm               4.66.1
transformers       4.33.1
typing_extensions  4.8.0
urllib3            2.0.3
websockets         10.4
wxPython           4.2.1
xformers           0.0.24
zipp               3.16.2

**Comment by cdb-boop** [comment]
I stopped the errors with `torch==2.1.2+cu121` and `xformers==0.0.23.post1`.

**Comment by brentjohnston** [comment]
I have same error, how to I modify torch==2.1.2+cu121 and xformers==0.0.23.post1 in comfyui? I'm not too familiar of where to put that. Do I pip install in main directory?

**Comment by cdb-boop** [comment]
Just make sure you have your virtual environment (Conda, Poetry, env, etc.) activated, if you're using one, and then I think you just need something like this
```
pip install torch==2.1.2+cu121 torchvision==0.16.2+cu121 xformers==0.0.23.post1 --index-url https://download.pytorch.org/whl/cu121
```

**Comment by brentjohnston** [comment]
I just added:

```
..\python_embeded\python.exe -s -m pip install torch==2.1.2+cu121 torchvision==0.16.2+cu121 xformers==0.0.23.post1 --index-url https://download.pytorch.org/whl/cu121
pause
```
under ComfyUI_windows_portable>update>update_comfyui_and_python_dependencies.bat and it's updating. Fingers crossed!

**Comment by brentjohnston** [comment]
I'm using portable version, would i just run `pip install torch==2.1.2+cu121 torchvision==0.16.2+cu121 xformers==0.0.23.post1 --index-url https://download.pytorch.org/whl/cu121` from \ComfyUI_windows_portable\python_embeded folder?

**Comment by brentjohnston** [comment]
Ok. it's working now with fresh comfyui portable install and following instructions. I think I missed the part about copying the model files to checkpoints folder the entire time. It was using another SDXL model to upscale..

**Comment by arlechinu** [comment]
Works now! Aye, only solution for me was a fresh install, seems to work but got some weird warning about ComfyUI\comfy\ldm\modules\attention.py:344: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)

Can ignore it and everything works fine, just odd. Cheers!

Guess it was the mismatch between xformers and torch and all that causing issues.

Thanks for the help :)
