### ISSUE TITLE
how can I apply a lora to sdxl model

### ISSUE THREAD

**Issue by szRush** [kijai/ComfyUI-SUPIR#75]
Thank you for updating
since sdxl model is filled in a panel， not a separate checkpoint loading node

**Comment by kijai** [comment]
Not currently possible directly, as the underlaying SUPIR pipeline doesn't support it. I wanted to look into adding the feature though, for now only way to do that is to save the checkpoint with the LoRA in Comfy first, it's clumsy but it works: 
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/40791699/46f42f42-21ae-4609-b469-6d4eed203919)

**Comment by Latentnaut** [comment]
it works and the outcome is better ;)

**Comment by kijai** [comment]
> it works and the outcome is better ;)

Can I ask you which lora did you use? I still need to test this myself, and find a way to apply it directly if it's really worth it.

**Comment by Latentnaut** [comment]
it was a Lora I made of my face, not public.

I noticed a slight improvement of the sharpness.

**Comment by kijai** [comment]
> it was a Lora I made of my face, not public.
> 
> I noticed a slight improvement of the sharpness.

Ok, understood, thank you for the info!

Also I did figure this out and you can now load it with these optional inputs:
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/40791699/88a1f3ac-5206-41fd-baca-b0ecd94e5962)

When they are used the sdxl_model -selection in the model loader is simply ignored, I don't want to remove it yet as it would break old workflows.

**Comment by HWiese1980** [comment]
Have there been changes around this? At least I see no error loading a lora into the SDXL model before giving it to SUPIR Model Loader... or how does it show that it doesn't work?

**Comment by kijai** [comment]
> Have there been changes around this? At least I see no error loading a lora into the SDXL model before giving it to SUPIR Model Loader... or how does it show that it doesn't work?

It has worked ever since I added the v2 loader node.

**Comment by HWiese1980** [comment]
Cool, I hadn't seen that anywhere. Although I have not noticed any difference in the result between using a lora and not using it.

**Comment by kijai** [comment]
> Cool, I hadn't seen that anywhere. Although I have not noticed any difference in the result between using a lora and not using it.

It does work, but generally you have to give it a bit more freedom to affect the image, as with full or high control strength SUPIR will try it's best to keep faithful to the original image. So that would be higher cfg and I find that lower control scale end value gives it enough freedom while still keeping most of the original.

Can't speak for all LoRAs of course, but I tried couple and they had an effect at least.
