### ISSUE TITLE
When process video,  raise the error "IndexError: list index out of range"

### ISSUE THREAD

**Issue by chflame163** [kijai/ComfyUI-SUPIR#76]
Hi, This plugin is the best upscale node I have ever seen.  Thank you for your great work.

When I used it to process video clips, this error occurred, I used the ```Load Video (Path)``` node of the [Video Helper Suite](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite) to load video files. How should I solve it?

`
[Tiled VAE]: input_size: torch.Size([1, 3, 864, 1536]), tile_size: 512, padding: 32
[Tiled VAE]: split to 2x3 = 6 tiles. Optimal tile size 512x416, original tile size 512x512
[Tiled VAE]: Executing Encoder Task Queue: 100%|████████████████████████████████████| 546/546 [00:02<00:00, 269.77it/s]
[Tiled VAE]: Done in 2.488s, max VRAM alloc 1445.591 MB
[Tiled VAE]: input_size: torch.Size([1, 3, 864, 1536]), tile_size: 512, padding: 32
[Tiled VAE]: split to 2x3 = 6 tiles. Optimal tile size 512x416, original tile size 512x512
[Tiled VAE]: Executing Encoder Task Queue: 100%|████████████████████████████████████| 546/546 [00:02<00:00, 271.05it/s]
[Tiled VAE]: Done in 2.488s, max VRAM alloc 1445.907 MB
captions:  [['']]
Tiled captioning
sampler_config:  {'target': '.sgm.modules.diffusionmodules.sampling.RestoreDPMPP2MSampler', 'params': {'num_steps': 10, 'restore_cfg': -1, 's_churn': 5, 's_noise': 1.035, 'discretization_config': {'target': '.sgm.modules.diffusionmodules.discretizer.LegacyDDPMDiscretization'}, 'guider_config': {'target': '.sgm.modules.diffusionmodules.guiders.LinearCFG', 'params': {'scale': 1.5, 'scale_min': 1.5}}, 'eta': 1.0}}
Sampled  1  of  57
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI-work\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-work\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-work\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes_v2.py", line 434, in sample
    _samples = self.sampler(denoiser, noised_z, cond=positive[i], uc=negative[i], x_center=sample.unsqueeze(0), control_scale=control_scale_end,
                                                     ~~~~~~~~^^^
IndexError: list index out of range
`

<img width="1843" alt="微信图片_20240319161320" src="https://github.com/kijai/ComfyUI-SUPIR/assets/130118553/764dd79d-592f-4340-9403-a72836f7f1d8">

**Comment by kijai** [comment]
Ok yeah sorry about that, was too focused on making it work with captioning batches, so that I missed the base case of not using captions. Should be fixed now.

**Comment by chflame163** [comment]
> Ok yeah sorry about that, was too focused on making it work with captioning batches, so that I missed the base case of not using captions. Should be fixed now.

It works very well now, Thanks.

**Comment by kijai** [comment]
> > Ok yeah sorry about that, was too focused on making it work with captioning batches, so that I missed the base case of not using captions. Should be fixed now.
> 
> It works very well now, Thanks.

Good to hear, thanks for the report!
