### ISSUE TITLE
Quick question regarding fp8

### ISSUE THREAD

**Issue by Archit01** [kijai/ComfyUI-SUPIR#77]
Does fp8 works with 8gb vram and 16gb ram ? Can it be implemented with tiling and offloading of models ? 
No matter if it is slow if it works I kindly request for this implementation.

**Comment by kijai** [comment]
It should fit 8GB VRAM with smallish dimensions/tile size with fp8, but I'm not sure if it all will fit 16GB RAM. Everything regarding that is already implemented.

**Comment by GaleBoro** [comment]
I've been able to run it with 8gb vram and 16gb ram with the following settings.
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/143328685/91fa6863-9a0a-4947-98c0-5bd09eeabb42)

**Comment by kijai** [comment]
> I've been able to run it with 8gb vram and 16gb ram with the following settings. ![image](https://private-user-images.githubusercontent.com/143328685/314500911-91fa6863-9a0a-4947-98c0-5bd09eeabb42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDEyMzEsIm5iZiI6MTcxMDk0MDkzMSwicGF0aCI6Ii8xNDMzMjg2ODUvMzE0NTAwOTExLTkxZmE2ODYzLTlhMGEtNDk0Ny05OGMwLTViZDA5ZWVhYmI0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxMzIyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2ZiYWJhNjM2MzNmZmQxZjAwMzUzZGNmNzQ1NWM5OWE1Y2E1MGJmMzUwZTM5NmU3MjEyODNlOTQxYjhhYTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BcLrnKwhrb-zgnCywxGpbxY0FzFc3EFrusNhaseeC8I)

Nice, that's very good to know!
