### ISSUE TITLE
Error occurred when executing SUPIR_model_loader

### ISSUE THREAD

**Issue by KurataHotaka** [kijai/ComfyUI-SUPIR#78]
I am getting this error during the model loading stage. This happened after the update, the error did not occur in the old version

Error occurred when executing SUPIR_model_loader:

Failed to load SUPIR model

File "D:\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes_v2.py", line 658, in process
raise Exception("Failed to load SUPIR model")

**Comment by kijai** [comment]
That is not much to go by... at that stage it's loading the SUPIR model itself and for some reason it can't, I would double check the model selection.

**Comment by KurataHotaka** [comment]
Ahh... I probably didn't update the path from another user's nodes setup. Sorry for bothering you on such an insignificant issue, but you told me the absolutely right solution! Thank you!

**Comment by kijai** [comment]
> Ahh... I probably didn't update the path from another user's nodes setup. Sorry for bothering you on such an insignificant issue, but you told me the absolutely right solution! Thank you!

Yeah that's common issue in Comfy in general, everyone has their models named differently within different paths, glad it wasn't more than that!
