### ISSUE TITLE
Error occurred when executing SUPIR_Upscale:

### ISSUE THREAD

**Issue by kakachiex2** [kijai/ComfyUI-SUPIR#8]
I get this error when executing node looks like it eats a lot of memory.

Error occurred when executing SUPIR_Upscale:

Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated : 11.99 GiB
Requested : 63.00 MiB
Device limit : 6.00 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
: 17179869184.00 GiB

File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-SUPIR\nodes.py", line 148, in process
image, = ImageScaleBy.upscale(self, image, resize_method, scale_by)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\nodes.py", line 1620, in upscale
s = comfy.utils.common_upscale(samples, width, height, upscale_method, "disabled")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\comfy\utils.py", line 416, in common_upscale
return lanczos(s, width, height)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\comfy\utils.py", line 395, in lanczos
return result.to(samples.device, samples.dtype)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by kijai** [comment]
I'm afraid it's not gonna run with that little VRAM, whole thing is very memory intensive.

**Comment by kakachiex2** [comment]
O men hope some optimization to be able to use it anyway thanks and great works as always

**Comment by kakachiex2** [comment]
my card is an RTX260 6Gib VRam

**Comment by kijai** [comment]
That is out of my hands currently, 6GB just isn't enough for the technique.
