### ISSUE TITLE
tiled_sampling missing in the SUPIR sampler node

### ISSUE THREAD

**Issue by Botoni** [kijai/ComfyUI-SUPIR#82]
The option is in the all in one supir upscale node, but not in the node by node workflow.

I've seen there's a supir tiles node, maybe that's what must be used, but I couldn't figure how.

**Comment by kijai** [comment]
This is now a chosen with the sampler option:
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/40791699/47c838fa-d430-40c9-85ca-6611d1ab71bf)
