### ISSUE TITLE
Malformed output image Tensor from 'SUPIR Decode' node?

### ISSUE THREAD

**Issue by cdb-boop** [kijai/ComfyUI-SUPIR#83]
I am piping the output of the 'SUPIR Decode' node into another node to blend an extracted face back into an image.

If I pipe the image output from SUPIR directly into the other node, I get blending artifacts:

![directly-blend-output](https://github.com/kijai/ComfyUI-SUPIR/assets/80225746/9ab3eb4b-0cf4-483e-a87f-c8c4206274b6)

However, if I save the SUPIR image output and load it manually then the image blends no problem:

![indirectly-blend-output](https://github.com/kijai/ComfyUI-SUPIR/assets/80225746/aa797cf9-d9e3-4232-91b8-3f8350c57ef2)

This leads me to suspect that the 'SUPIR Decode' node is outputting a malformed image Tensor.

**Comment by kijai** [comment]
Yeah you are right, the output from the SUPIR VAE is bit out of range, clamping it to 0.0 - 1.0 now.
