### ISSUE TITLE
Please Explain the New "SUPIR Tiles" Node

### ISSUE THREAD

**Issue by camoody1** [kijai/ComfyUI-SUPIR#85]
Thank you again for your great work.

I'm just wondering if you could please explain where I should use the new "SUPIR Tiles" node that is now available with your version 2. The workflow I'm currently using doesn't have this node and neither does your sample here in this Git.  Could you please tell us what it does and how it should be used?

Thanks

**Comment by kijai** [comment]
> Thank you again for your great work.
> 
> I'm just wondering if you could please explain where I should use the new "SUPIR Tiles" node that is now available with your version 2. The workflow I'm currently using doesn't have this node and neither does your sample here in this Git.  Could you please tell us what it does and how it should be used?
> 
> Thanks

It's meant to be used as a helper to generate captions for the tiles. The way it tiles the image is the same way the Tiled SUPIR samplers do it. The conditioning node should already support it, but it requires the input to be a list of prompt lists, for which I made a node in my moondream nodes to output. 

Moondream proved to not be good enough for this though, I've been meaning to find a better alternative, so this is work in progress.

**Comment by kijai** [comment]
> So, just to be clear, it's not a node that we need to use in our general workflows?

Not at all, it's mostly experimental for now.

**Comment by camoody1** [comment]
Sounds good. Thank you for your quick response and have a great Sunday!
