### ISSUE TITLE
Crash on both loaders with no error message

### ISSUE THREAD

**Issue by ifilipis** [kijai/ComfyUI-SUPIR#88]
Steps to reproduce the issue

1. Create an L4 instance on Google Cloud
2. Install NVIDIA drivers
3. Install ComfyUI and ComfyUI Manager
4. Install this repo
5. With either loader, it would crash without any error after
[2024-03-24 18:49] Attempting to load SDXL model from node inputs
[2024-03-24 18:49] Requested to load SDXL
[2024-03-24 18:49] Loading 1 new model

In the legacy loader, it would crash on attempting to load SDXL from the file

Tried with or without xformers
Every FP setting
Tried SDXL 1.0 Base, Juggernaut XL V8, V9
Tried commits from 2 weeks ago

Same result every time

I guess I'm missing some dependencies or something else. Also I checked that SDXL works fine on its own

**Comment by kijai** [comment]
How much RAM does that instance have? I updated the v2 loader a bit today to reduce it's memory use, not sure if it can further reduced. Crashing without error would suggest running out of memory.

**Comment by ifilipis** [comment]
24GB VRAM, 32GB RAM. Let me try to increase it and see what happens

I also forgot to mention that it also says clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight', 'clip_g.logit_scale'] when using checkpoint loader

**Comment by kijai** [comment]
> 24GB VRAM, 32GB RAM. Let me try to increase it and see what happens
> 
> I also forgot to mention that it also says clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight', 'clip_g.logit_scale'] when using checkpoint loader

That seems to be a comfy thing as it says that with just the normal Comfy node, I get that too and it works so it's  unrelated to this.

You have the very latest version? I changed the model load order, admittedly it was spiking RAM usage before.

**Comment by ifilipis** [comment]
Alright, apparently, increasing RAM to 54GB helped. But I would have never guessed, as the task manager showed that it never went above 17GB

Thank you so much!
